"""Walk-forward validation engine module.

Provides functions for generating rolling train/test folds, executing walk-forward
backtests with parameter optimization and indicator warm-up buffers, and aggregating
out-of-sample performance results across folds.
"""

from typing import Any
import pandas as pd

from quantlab.backtest.engine import extract_metrics, run_backtest
from quantlab.strategies.sma_crossover import generate_signals


def generate_folds(
    pool_start: str,
    pool_end: str,
    train_months: int = 9,
    test_months: int = 3,
) -> list[dict[str, pd.Timestamp]]:
    """Generate non-overlapping, sequential train and test date folds.

    Folds are generated starting from pool_start. Each fold consists of a training
    window of duration train_months followed immediately by a testing window of
    duration test_months. Fold generation stops when a full train+test fold can
    no longer fit entirely within [pool_start, pool_end].

    Args:
        pool_start: Start date string of the total available pool (e.g. "2018-01-01").
        pool_end: End date string of the total available pool (e.g. "2024-01-01").
        train_months: Duration of training window in months. Default 9.
        test_months: Duration of test window in months. Default 3.

    Returns:
        list[dict[str, pd.Timestamp]]: List of fold dictionaries, each containing:
            - train_start (pd.Timestamp)
            - train_end (pd.Timestamp)
            - test_start (pd.Timestamp)
            - test_end (pd.Timestamp)

    Raises:
        ValueError: If train_months <= 0, test_months <= 0, or pool_start >= pool_end.
    """
    if train_months <= 0 or test_months <= 0:
        raise ValueError(
            f"train_months ({train_months}) and test_months ({test_months}) must be > 0."
        )

    start_ts = pd.Timestamp(pool_start)
    end_ts = pd.Timestamp(pool_end)

    if start_ts >= end_ts:
        raise ValueError(
            f"pool_start ('{pool_start}') must be strictly earlier than pool_end ('{pool_end}')."
        )

    folds: list[dict[str, pd.Timestamp]] = []
    current_start = start_ts

    while True:
        train_end = current_start + pd.DateOffset(months=train_months)
        test_start = train_end
        test_end = test_start + pd.DateOffset(months=test_months)

        if test_end > end_ts:
            break

        folds.append(
            {
                "train_start": current_start,
                "train_end": train_end,
                "test_start": test_start,
                "test_end": test_end,
            }
        )
        current_start = test_end

    return folds


def _align_tz(ts: pd.Timestamp, target_tz: Any) -> pd.Timestamp:
    """Align a Timestamp's timezone with target_tz."""
    if target_tz is None:
        if ts.tz is not None:
            return ts.tz_localize(None)
        return ts
    else:
        if ts.tz is None:
            return ts.tz_localize(target_tz)
        return ts.tz_convert(target_tz)


def run_walk_forward(
    close: pd.Series,
    folds: list[dict[str, pd.Timestamp]],
    fast_windows: list[int],
    slow_windows: list[int],
    min_trades: int = 10,
    init_cash: float = 10_000.0,
    fees: float = 0.001,
    slippage: float = 0.001,
) -> list[dict[str, Any]]:
    """Execute walk-forward validation across generated folds.

    For each fold:
    1. Computes SMA signals for train window with lookback buffer max(slow_windows) days.
    2. Runs parameter sweep on train window.
    3. Selects winning config with total_trades >= min_trades, highest sharpe_ratio
       (tie-breaker: smaller max_drawdown magnitude).
    4. If no valid config meets min_trades, marks fold "skipped_no_valid_config".
    5. Evaluates winning config on test window (OOS) with lookback buffer, starting flat.

    Args:
        close: Pandas Series of close prices.
        folds: List of fold dicts generated by generate_folds.
        fast_windows: List of fast SMA window lookbacks to evaluate.
        slow_windows: List of slow SMA window lookbacks to evaluate.
        min_trades: Minimum trades required in train window for candidate selection.
        init_cash: Initial cash for portfolio simulation. Default 10000.0.
        fees: Fee rate per trade. Default 0.001 (0.1%).
        slippage: Slippage rate per trade. Default 0.001 (0.1%).

    Returns:
        list[dict[str, Any]]: One dictionary per fold containing fold metadata, status,
        selected configuration parameters, train metrics, and out-of-sample test metrics.
    """
    if not slow_windows:
        max_slow = 0
    else:
        max_slow = max(slow_windows)

    target_tz = close.index.tz if isinstance(close.index, pd.DatetimeIndex) else None
    results: list[dict[str, Any]] = []

    for fold in folds:
        train_start = _align_tz(fold["train_start"], target_tz)
        train_end = _align_tz(fold["train_end"], target_tz)
        test_start = _align_tz(fold["test_start"], target_tz)
        test_end = _align_tz(fold["test_end"], target_tz)

        # 1. Train window parameter sweep with lookback buffer
        train_buf_start = train_start - pd.Timedelta(days=max_slow)
        close_train_buf = close[
            (close.index >= train_buf_start) & (close.index < train_end)
        ]
        close_train_win = close[
            (close.index >= train_start) & (close.index < train_end)
        ]

        candidates = []
        if len(close_train_win) > 0:
            for fast in fast_windows:
                for slow in slow_windows:
                    if fast >= slow:
                        continue
                    entries_buf, exits_buf = generate_signals(
                        close_train_buf, fast_window=fast, slow_window=slow
                    )
                    entries_win = entries_buf.loc[close_train_win.index]
                    exits_win = exits_buf.loc[close_train_win.index]

                    portfolio = run_backtest(
                        close=close_train_win,
                        entries=entries_win,
                        exits=exits_win,
                        init_cash=init_cash,
                        fees=fees,
                        slippage=slippage,
                    )
                    metrics = extract_metrics(portfolio)
                    candidates.append(
                        {
                            "fast": fast,
                            "slow": slow,
                            "metrics": metrics,
                        }
                    )

        valid_candidates = [
            c
            for c in candidates
            if c["metrics"]["total_trades"] >= min_trades
            and c["metrics"]["sharpe_ratio"] is not None
        ]

        if not valid_candidates:
            results.append(
                {
                    "train_start": train_start,
                    "train_end": train_end,
                    "test_start": test_start,
                    "test_end": test_end,
                    "status": "skipped_no_valid_config",
                    "selected_fast": None,
                    "selected_slow": None,
                    "train_metrics": None,
                    "oos_metrics": None,
                }
            )
            continue

        # 2. Select winning candidate: highest sharpe_ratio, tie-break by smaller max_drawdown magnitude
        best_candidate = max(
            valid_candidates,
            key=lambda c: (
                c["metrics"]["sharpe_ratio"],
                -abs(c["metrics"]["max_drawdown"])
                if c["metrics"]["max_drawdown"] is not None
                else float("-inf"),
            ),
        )

        selected_fast = best_candidate["fast"]
        selected_slow = best_candidate["slow"]
        train_metrics = best_candidate["metrics"]

        # 3. Evaluate selected config on test window (OOS) with lookback buffer
        test_buf_start = test_start - pd.Timedelta(days=max_slow)
        close_test_buf = close[
            (close.index >= test_buf_start) & (close.index < test_end)
        ]
        close_test_win = close[(close.index >= test_start) & (close.index < test_end)]

        if len(close_test_win) > 0:
            entries_buf_test, exits_buf_test = generate_signals(
                close_test_buf, fast_window=selected_fast, slow_window=selected_slow
            )
            entries_test = entries_buf_test.loc[close_test_win.index]
            exits_test = exits_buf_test.loc[close_test_win.index]

            portfolio_test = run_backtest(
                close=close_test_win,
                entries=entries_test,
                exits=exits_test,
                init_cash=init_cash,
                fees=fees,
                slippage=slippage,
            )
            oos_metrics = extract_metrics(portfolio_test)
        else:
            oos_metrics = {
                "total_return": None,
                "sharpe_ratio": None,
                "max_drawdown": None,
                "win_rate": None,
                "total_trades": 0,
            }

        results.append(
            {
                "train_start": train_start,
                "train_end": train_end,
                "test_start": test_start,
                "test_end": test_end,
                "status": "ok",
                "selected_fast": selected_fast,
                "selected_slow": selected_slow,
                "train_metrics": train_metrics,
                "oos_metrics": oos_metrics,
            }
        )

    return results


def aggregate_walk_forward_results(fold_results: list[dict[str, Any]]) -> dict[str, Any]:
    """Aggregate out-of-sample performance metrics across evaluated walk-forward folds.

    Args:
        fold_results: List of fold dictionaries returned by run_walk_forward.

    Returns:
        dict[str, Any] containing aggregated walk-forward performance metrics:
            - folds_total (int): Total number of generated folds.
            - folds_evaluated (int): Number of evaluated folds with status 'ok'.
            - folds_skipped (int): Number of skipped folds with status 'skipped_no_valid_config'.
            - avg_oos_return (float | None): Average total return across evaluated folds.
            - avg_oos_sharpe (float | None): Average Sharpe ratio across evaluated folds.
            - worst_oos_drawdown (float | None): Single worst max drawdown across evaluated folds.
            - pct_folds_profitable (float | None): Fraction of evaluated folds with oos total_return > 0.
            - total_oos_trades_summed (int): Sum of all out-of-sample trades across evaluated folds.
            - selected_configs_per_fold (list[tuple[int, int]]): List of (fast, slow) tuples for evaluated folds.

    Note:
        If folds_evaluated == 0, all average and rate fields (avg_oos_return, avg_oos_sharpe,
        worst_oos_drawdown, pct_folds_profitable) are returned as None instead of crashing or NaN.
    """
    folds_total = len(fold_results)
    evaluated_folds = [f for f in fold_results if f.get("status") == "ok"]
    folds_evaluated = len(evaluated_folds)
    folds_skipped = folds_total - folds_evaluated

    if folds_evaluated == 0:
        return {
            "folds_total": folds_total,
            "folds_evaluated": 0,
            "folds_skipped": folds_skipped,
            "avg_oos_return": None,
            "avg_oos_sharpe": None,
            "worst_oos_drawdown": None,
            "pct_folds_profitable": None,
            "total_oos_trades_summed": 0,
            "selected_configs_per_fold": [],
        }

    selected_configs_per_fold = [
        (f["selected_fast"], f["selected_slow"]) for f in evaluated_folds
    ]

    total_oos_trades_summed = sum(
        f["oos_metrics"]["total_trades"]
        for f in evaluated_folds
        if f.get("oos_metrics") and f["oos_metrics"].get("total_trades") is not None
    )

    returns = [
        f["oos_metrics"]["total_return"]
        for f in evaluated_folds
        if f.get("oos_metrics") and f["oos_metrics"].get("total_return") is not None
    ]
    avg_oos_return = (sum(returns) / len(returns)) if returns else None

    sharpes = [
        f["oos_metrics"]["sharpe_ratio"]
        for f in evaluated_folds
        if f.get("oos_metrics") and f["oos_metrics"].get("sharpe_ratio") is not None
    ]
    avg_oos_sharpe = (sum(sharpes) / len(sharpes)) if sharpes else None

    drawdowns = [
        f["oos_metrics"]["max_drawdown"]
        for f in evaluated_folds
        if f.get("oos_metrics") and f["oos_metrics"].get("max_drawdown") is not None
    ]
    worst_oos_drawdown = min(drawdowns) if drawdowns else None

    profitable_count = sum(
        1
        for f in evaluated_folds
        if f.get("oos_metrics")
        and f["oos_metrics"].get("total_return") is not None
        and f["oos_metrics"]["total_return"] > 0
    )
    pct_folds_profitable = (
        float(profitable_count) / folds_evaluated if folds_evaluated > 0 else None
    )

    return {
        "folds_total": folds_total,
        "folds_evaluated": folds_evaluated,
        "folds_skipped": folds_skipped,
        "avg_oos_return": avg_oos_return,
        "avg_oos_sharpe": avg_oos_sharpe,
        "worst_oos_drawdown": worst_oos_drawdown,
        "pct_folds_profitable": pct_folds_profitable,
        "total_oos_trades_summed": total_oos_trades_summed,
        "selected_configs_per_fold": selected_configs_per_fold,
    }
